version: '3.8'

services:
  jekyll-site:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app
      - bundle:/usr/src/app/vendor/bundle
    environment:
      - JEKYLL_ENV=development
      - BUNDLE_PATH=/usr/src/app/vendor/bundle
    command: sh -c "bundle install && bundle exec jekyll serve -H 0.0.0.0 -w"

volumes:
  bundle:
