version: '3.8'

services:
  jekyll-site:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/vendor
      - /usr/src/app/.bundle
    environment:
      - JEKYLL_ENV=development
    command: bundle exec jekyll serve -H 0.0.0.0 -w --livereload